baseURL = "https://travellingsky.github.io"
languageCode = "en-us"
title = "Travelling Sky"
theme = "massively"
disqusShortname = "travellingsky"
googleAnalytics = ""

[related]
threshold = 80
includeNewer = true
toLower = false

[[related.indices]]
name = "keywords"
weight = 100
[[related.indices]]
name  = "date"
weight = 10
pattern = "2006"


# set below parameter to define a favicon
[params]
  favicon = "/favicon.png"
  author = "Shetal Gandhi"
  site_description = "Your guide to the worlds best travel destinations."
  description = "Your guide to the worlds best travel destinations."

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]

# Below parameters can be set to override default post settings
[params.posts]
     foldername = "blog"
     pagesize = "10"
     featuredpost = "false"

[permalinks]
  blog = "/blog/:title/"

[taxonomies]
  category = "categories"

[languages]
[languages.en]
  languageName = "English"

