---
new_page_extension: html
auto_deploy: true
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
upload_dir: content/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.54.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.54.0
