name: Push to GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Deploy the site
        uses: amitgandhinz/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.57.2
          TARGET_REPO: travellingsky/travellingsky.github.io
          TOKEN: ${{ secrets.TOKEN }}