name: Deploy Website
# This workflow is triggered on pushes to the repository.
on: 
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and Deploy
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      # This step uses GitHub's checkout action to pull the latest code
      - name: Checkout Master
        uses: actions/checkout@master

      - name: Deploy the site
        uses: benmatselby/hugo-deploy-gh-pages@master
        env:
          HUGO_VERSION: 0.57.2
          TARGET_REPO: travellingsky/travellingsky.github.io
          TOKEN: ${{ secrets.TOKEN }}