name: Deploy Website
# This workflow is triggered on pushes to the repository.
on: 
  push:
    branches:
      - master

jobs:
  build-deploy:
    name: Build and Deploy
    # This job runs on Linux
    runs-on: ubuntu-18.04
    steps:
      # This step uses GitHub's checkout action to pull the latest code
      - name: Check out the code
        uses: actions/checkout@master

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.1.0
        with: 
          hugo-version: '0.58.2'

      - name: Build
        run: hugo --gc --cleanDestinationDir -t parsa-hugo --config config-prod.toml

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.3.1
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public